version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pesantren-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pesantren
      POSTGRES_PASSWORD: pesantren123
      POSTGRES_DB: pesantren_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pesantren -d pesantren_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
